name: Pre-Commit Checks

on:
  pull_request:

jobs:
  pre-commit:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tfenv
        uses: rhythmictech/actions-setup-tfenv@v0.0.4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install prerequisites
        run: cat .github/script/pre-commit.sh | bash

      - name: Install Terraform version
        run: tfenv install

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files
